#!/usr/bin/env bash
#This script configures a new ubuntu machine with
# with HAproxy load balancer

sudo apt-get update -y
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
frontend http_front
        bind *:80
        mode http
        default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 35.174.204.79:80 check
    server web-02 34.227.91.64:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy reload
